name: 'Pretty Profile README'
author: gccio
description: 'generate README.md with github and wakatime data'

inputs:
  GH_TOKEN:
    description: 'GitHub access token with repo and user scope'
    required: true
    default: ${{ github.token }}

  WAKATIME_API_KEY:
    description: 'Your Wakatime API Key'
    required: true

  TIMEZONE:
    description: 'Your timezone'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'activity'
  color: 'orange'
